# python padim_main.py --seed 0 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 0 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 0 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 0 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "4"
# python padim_main.py --seed 0 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1-2"
# python padim_main.py --seed 0 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1-3"
# python padim_main.py --seed 0 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 0 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 0 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 0 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "3-4"
# python padim_main.py --seed 0 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 0 --data_category "cable" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 0 --data_category "cable" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 0 --data_category "cable" --arch "wide_resnet50_2" --use_layers "4"
# python padim_main.py --seed 0 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 0 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 0 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 0 --data_category "cable" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 0 --data_category "cable" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 0 --data_category "cable" --arch "wide_resnet50_2" --use_layers "3-4"
# python padim_main.py --seed 0 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 0 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 0 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 0 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "4"
python padim_main.py --seed 0 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 0 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 0 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 0 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 0 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 0 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "3-4"
# python padim_main.py --seed 0 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 0 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 0 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 0 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "4"
python padim_main.py --seed 0 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 0 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 0 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 0 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 0 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 0 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "3-4"


# python padim_main.py --seed 1 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 1 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 1 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 1 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "4"
python padim_main.py --seed 1 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 1 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 1 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 1 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 1 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 1 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "3-4"
# python padim_main.py --seed 1 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 1 --data_category "cable" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 1 --data_category "cable" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 1 --data_category "cable" --arch "wide_resnet50_2" --use_layers "4"
python padim_main.py --seed 1 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 1 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 1 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 1 --data_category "cable" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 1 --data_category "cable" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 1 --data_category "cable" --arch "wide_resnet50_2" --use_layers "3-4"
# python padim_main.py --seed 1 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 1 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 1 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 1 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "4"
python padim_main.py --seed 1 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 1 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 1 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 1 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 1 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 1 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "3-4"
# python padim_main.py --seed 1 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 1 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 1 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 1 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "4"
python padim_main.py --seed 1 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 1 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 1 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 1 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 1 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 1 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "3-4"


# python padim_main.py --seed 2 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 2 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 2 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 2 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "4"
python padim_main.py --seed 2 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 2 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 2 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 2 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 2 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 2 --data_category "bottle" --arch "wide_resnet50_2" --use_layers "3-4"
# python padim_main.py --seed 2 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 2 --data_category "cable" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 2 --data_category "cable" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 2 --data_category "cable" --arch "wide_resnet50_2" --use_layers "4"
python padim_main.py --seed 2 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 2 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 2 --data_category "cable" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 2 --data_category "cable" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 2 --data_category "cable" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 2 --data_category "cable" --arch "wide_resnet50_2" --use_layers "3-4"
# python padim_main.py --seed 2 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 2 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 2 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 2 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "4"
python padim_main.py --seed 2 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 2 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 2 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 2 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 2 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 2 --data_category "carpet" --arch "wide_resnet50_2" --use_layers "3-4"
# python padim_main.py --seed 2 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1"
# python padim_main.py --seed 2 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "2"
# python padim_main.py --seed 2 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "3"
# python padim_main.py --seed 2 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "4"
python padim_main.py --seed 2 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1-2"
python padim_main.py --seed 2 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1-3"
python padim_main.py --seed 2 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "1-4"
# python padim_main.py --seed 2 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "2-3"
# python padim_main.py --seed 2 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "2-4"
# python padim_main.py --seed 2 --data_category "hazelnut" --arch "wide_resnet50_2" --use_layers "3-4"

